DATA BEGIN OF ITAB.
DATA BUKRS LIKE T001-BUKRS.
DATA END OF ITAB.

perform get_company_data.


FORM GET_COMPANY_data.

  DATA : ES_T001 TYPE T001.
  DATA : ES_ADRC TYPE ADRC.

  DATA : V_BUKRS LIKE T001-BUKRS,
         V_SPRAS LIKE T001-SPRAS.

  V_BUKRS = iTAB-bukrs.

  CLEAR ES_T001.
  SELECT SINGLE * FROM T001 INTO ES_T001
  WHERE BUKRS = V_BUKRS.

  CLEAR ES_ADRC.
  SELECT SINGLE * FROM ADRC INTO ES_ADRC
  WHERE ADDRNUMBER = ES_T001-ADRNR.

ENDFORM.
