
TYPES: BEGIN OF ITAB_TYPES,
         BUKRS LIKE T001-BUKRS,
         KUNNR LIKE KNA1-KUNNR.
TYPES:END OF ITAB_TYPES.

TYPES: BEGIN OF TYP_CUR ,
         WAERS TYPE WAERS,
       END OF TYP_CUR.

DATA: TAB_CUR TYPE STANDARD TABLE OF TYP_CUR WITH HEADER LINE.
DATA ITAB TYPE ITAB_TYPES.


PERFORM GET_BANK_DATA .


FORM GET_BANK_DATA .


  DATA: V_BUKRS LIKE T001-BUKRS,
        V_KUNNR LIKE KNA1-KUNNR.

  DATA: ES_T012K     TYPE T012K,
        ES_T012T     TYPE T012T,
        ES_TIBAN     TYPE TIBAN,
        ES_BNKA      TYPE BNKA,
        ES_T001_ADRC TYPE ADRC.


  DATA: LT_T012K TYPE TABLE OF T012K WITH HEADER LINE,
        LV_LINES TYPE N,
        LV_KTOKD LIKE KNA1-KTOKD,
        LV_WAERS TYPE WAERS.

  CLEAR: ES_T012K, ES_T012T, ES_TIBAN, ES_BNKA, ES_T001_ADRC.

*  -----------------------------------------------------------------


  V_BUKRS = iTAB-bukrs.
  V_KUNNR = iTAB-kunnr.

  CLEAR LV_KTOKD.
  SELECT SINGLE KTOKD FROM KNA1 INTO LV_KTOKD
  WHERE KUNNR = V_KUNNR.

  IF SY-SUBRC <> 0 AND LV_KTOKD <> '3100' .
    CALL FUNCTION 'CONVERSION_EXIT_ALPHA_INPUT'
      EXPORTING
        INPUT  = V_KUNNR
      IMPORTING
        OUTPUT = V_KUNNR.
  ENDIF.

  CLEAR: TAB_CUR[] , TAB_CUR .
  SELECT WAERS FROM BSID
  APPENDING CORRESPONDING FIELDS OF TABLE TAB_CUR
    WHERE KUNNR = V_KUNNR
      AND BUKRS = V_BUKRS.

  SORT TAB_CUR ASCENDING BY WAERS.
  DELETE ADJACENT DUPLICATES FROM TAB_CUR.

  DESCRIBE TABLE TAB_CUR LINES LV_LINES.

  CLEAR LV_WAERS.
  IF LV_LINES > 1 .
    SELECT SINGLE * FROM T012K INTO ES_T012K
       WHERE BUKRS = V_BUKRS
       AND   WAERS = 'GBP'
       AND   HBKID = 'RBSC'.

    LV_WAERS = 'GBP'.

  ELSE.

    READ TABLE TAB_CUR INDEX 1.
    SELECT SINGLE * FROM T012K INTO ES_T012K
      WHERE BUKRS = V_BUKRS
      AND   WAERS = TAB_CUR-WAERS
      AND   HBKID = 'RBSC'.

    LV_WAERS = TAB_CUR-WAERS.
  ENDIF.


*  -------------------------------------------------------------------
  IF SY-SUBRC = 0.
    SELECT SINGLE * FROM T012T INTO ES_T012T
      WHERE SPRAS = 'E'
      AND BUKRS = ES_T012K-BUKRS
      AND HBKID = ES_T012K-HBKID
      AND HKTID = ES_T012K-HKTID.

    SELECT SINGLE * FROM TIBAN INTO ES_TIBAN
      WHERE BANKN = ES_T012K-BANKN.


    SELECT SINGLE * FROM BNKA INTO ES_BNKA
      WHERE BANKS = ES_TIBAN-BANKS
      AND   BANKL = ES_TIBAN-BANKL.

    SELECT SINGLE * FROM ADRC INTO ES_T001_ADRC
      WHERE ADDRNUMBER = ES_BNKA-ADRNR.

  ENDIF.


ENDFORM.
