DATA BEGIN OF ITAB.
  DATA bukrs LIKE ekko-BUKRS.
  data spras like LFA1-SPRAS.

DATA END OF ITAB.


FORM GET_ADDRESSDATA .

  DATA ES_ADRC TYPE ADRC.
  DATA ES_T001 TYPE T001.
  DATA ES_T618T TYPE T618T.
  DATA ES_T005U TYPE T005U.
  DATA ES_T005T TYPE T005T.
  DATA ES_EIKP TYPE EIKP.

  DATA IV_BUKRS LIKE T001-BUKRS.
  DATA IV_SPRAS TYPE C LENGTH 2.
  DATA IV_COUNTRY TYPE LANDX.

  IV_BUKRS = iTAB-bukrs.
  IV_SPRAS = iTAB-spras.

  TRANSLATE IV_SPRAS TO UPPER CASE.

  CLEAR ES_T001.
  SELECT SINGLE * FROM T001 INTO ES_T001 WHERE BUKRS = IV_BUKRS.

  CLEAR: ES_ADRC, ES_T005T, ES_T005U, ES_EIKP, ES_T618T.


  SELECT SINGLE * FROM ADRC INTO ES_ADRC
  WHERE ADDRNUMBER = ES_T001-ADRNR AND NATION = ' '.
  SELECT SINGLE * FROM T005T INTO ES_T005T
  WHERE SPRAS = SY-LANGU AND LAND1 = ES_ADRC-COUNTRY.


ENDFORM.                    "get_addressdata'
